### ISSUE TITLE
New pack available

### ISSUE THREAD

**Issue by PaoloP74** [watterott/ATmega328PB-Testing#10]
v1.1.130 --> http://packs.download.atmel.com/

ChageLog
1.1.130 Fix bitfields of PRR registers for PWM devices. Remove XDIV in ATmega128. Update CFD fuse for **ATmega328PB**
1.0.118 Fix bitfield and register name issues for all 'Timer/Counter, 16-bit' for ATmega324PB
1.0.105 Add PCINT[0,7] to ATmega2564 IO header
1.0.98  Removed Full-Swing Crystal field for SUT_CKSEL of ATmega PB devices. Updated documentation links
1.0.91  Initial release

**Comment by awatterott** [comment]
I have updated the files.
