### ISSUE TITLE
Missing pins on 328PB

### ISSUE THREAD

**Issue by jandrewb** [watterott/ATmega328PB-Testing#15]
The pins_arduino.h file does not appear to define PB6, PB7, and PC6. These pins didn't exist on the 328P.

**Comment by awatterott** [comment]
The pins are also available on a 328P, but they are not defined because they have special functions.
PB6 - XTAL1 (for crystal)
PB7 - XTAL1 (for crystal)
PC6 - Reset

**Comment by jandrewb** [comment]
Right... I guess they are still accessible through the AVR APIs.
