### ISSUE TITLE
Serial not defined

### ISSUE THREAD

**Issue by szwetsloot** [watterott/ATmega328PB-Testing#25]
When trying to use these board definitions with the arduino IDE I get:
Main:106: error: 'Serial' was not declared in this scope
Serial.begin(9600);

Dummy code which throws same error:
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
}

void loop() {
  // put your main code here, to run repeatedly:

}

**Comment by awatterott** [comment]
Which IDE and AVR core version do you use?

**Comment by szwetsloot** [comment]
avrdude: Version 6.3, compiled on Jan 17 2017 at 12:00:53
Arduino IDE 1.8.5

**Comment by awatterott** [comment]
Do you have installed the AVR core 1.6.200? The built-in core has no support for the ATmega328PB.
https://downloads.arduino.cc/packages/package_avr_3.6.0_index.json

**Comment by szwetsloot** [comment]
Does that include either this one:
![image](https://user-images.githubusercontent.com/8173546/33516070-6ec4b198-d76c-11e7-9968-5d43d10b4b39.png)
Or this one:
![image](https://user-images.githubusercontent.com/8173546/33516074-7f8874b0-d76c-11e7-8162-d06f0f63c64b.png)
?

If not, can youtell me how to install it?

**Comment by awatterott** [comment]
Add the [link](https://downloads.arduino.cc/packages/package_avr_3.6.0_index.json) under File->Preferences and then install the board with Tools->Board->Boards Manager

**Comment by szwetsloot** [comment]
Sorry for the stupid questions, which board do you mean?

**Comment by szwetsloot** [comment]
Is Arduino AVR Board 1.6.200 the same as Arduino AVR Board 1.6.20?
I can't uninstall and reinstall that package.
I tried to downgrade to Arduino AVR Board 1.6.19 and upgrade to Arduino AVR Board 1.6.20 again, but that did not change anything.

**Comment by awatterott** [comment]
No, 1.6.20 is not 1.6.200. You have to add the link before you can install the new board.

**Comment by szwetsloot** [comment]
I though I did, but apparently misclicked.
That resolved my issue.
Thank you for the quick help!
