### ISSUE TITLE
'Serial' was not declared in this scope

### ISSUE THREAD

**Issue by StephiB** [watterott/ATmega328PB-Testing#27]
Using 1.8.5 IDE and AVR Boards 1.6.20 tried many different combinations but without success.
Always the same error if Serial is called in setup:
DigitalReadSerial:27: error: 'Serial' was not declared in this scope

   Serial.println(buttonState);

   ^

exit status 1
'Serial' was not declared in this scope

**Comment by awatterott** [comment]
For the mega328PB you will need the AVR Boards **1.6.200**. Further infos [here](https://github.com/arduino/toolchain-avr/pull/47)
