### ISSUE TITLE
PWM on arduino pins 0, 1 and 2

### ISSUE THREAD

**Issue by Xplorer001** [watterott/ATmega328PB-Testing#3]
I was porting the code to our Atmega328pb board named Tit; noticed that the additional PWM output pins 0, 1 and 2 do not work..

The fix is simple, as you may already know it :), is to define relevant timers on pins_arduino.h file. 

#if defined(__AVR_ATmega328PB__)
	TIMER3A,
	TIMER4A,
	TIMER4B,
#else
	NOT_ON_TIMER, /* 0 - port D */
	NOT_ON_TIMER,	
	NOT_ON_TIMER,
	// on the ATmega168, digital pin 3 has hardware pwm
#endif	

Will send a pull request once all the testing is done.
`

**Comment by awatterott** [comment]
Thank you for the info. I have added the timers.
