### ISSUE TITLE
Connot compile

### ISSUE THREAD

**Issue by sicsim** [watterott/ATmega328PB-Testing#34]
Hi 
I'm getting errors when trying to compile a simple blinky example.
![screenshot from 2018-04-21 13-30-38](https://user-images.githubusercontent.com/28184849/39083668-64ba1ebc-4568-11e8-91ac-236333ea9820.png)

**Comment by awatterott** [comment]
Please update the Arduino AVR Boards to version 1.6.206.
https://github.com/watterott/ATmega328PB-Testing#installation-on-arduino-ide-18

**Comment by sicsim** [comment]
Hi.
Mine is already on 1.6.21. Is that an issue?

**Comment by awatterott** [comment]
You need **1.6.206**.

**Comment by sicsim** [comment]
Wonderful. It went well. Thanks.
