### ISSUE TITLE
Dead chips

### ISSUE THREAD

**Issue by LuisCRSousa** [watterott/ATmega328PB-Testing#44]
After tried to upload this bootloader to my custom 3.3V and external 8MHz  the chip loats connection to the ISP MKII and ICE. I can't get it even to read the fuses using the atmel studio tools

**Comment by awatterott** [comment]
How do you have programmed the bootloader? If you have used the Arduino IDE, which board have you selected?
Please also post a schematic of your custom board.

**Comment by LuisCRSousa** [comment]
Programmed with Arduino IDE and selected 328pb 3.3V 8Mhz external. Tested with 3 chips, all dead after bootloader. All worked fine before the upload.

**Comment by awatterott** [comment]
For a crystal oscillator or ceramic resonators you have to select "Crystal Clock".
"External Clock" is for an active ext. clock source.
