### ISSUE TITLE
USART1 instead of USART0

### ISSUE THREAD

**Issue by zdravke** [watterott/ATmega328PB-Testing#47]
I'm suspecting optiboot_m328pb.hex is using USART0. Is there a way to use USART1 instead?

**Comment by awatterott** [comment]
Yes, as default USART0 is used. To use another USART interface, Optiboot has to be re-complied with UART set to the respective port: https://github.com/watterott/Wattuino/blob/master/software/Optiboot/optiboot.c#L127
