### ISSUE TITLE
m328pb flash programming using UART.

### ISSUE THREAD

**Issue by bhargavmakodia** [watterott/ATmega328PB-Testing#49]
Dear @awatterott ,

after programming ATmega328pb using arduino as ISP, we can program it using USB - UART bridge only ONCE.

After successful uploading of program once, if we wish to program it again using UART it shows error.
`avrdude.exe: stk500_recv(): programmer is not responding` 

A response is awaited from your side.
Thank you!
BM.

**Comment by awatterott** [comment]
Please check the things, I have written before:
https://github.com/watterott/ATmega328PB-Testing/issues/48#issuecomment-446910644
