### ISSUE TITLE
New toolchain 3.5.2 with libc 2.0.0.

### ISSUE THREAD

**Issue by PaoloP74** [watterott/ATmega328PB-Testing#6]
Atmel AVR GNU Toolchain **3.5.2** available.
--> http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORWINDOWS.aspx
--> http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORLINUX.aspx
--> http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/3.5.2/

**Comment by awatterott** [comment]
I have updated the Windows files to toolchain 3.5.2 and device pack 1.0.98
